version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pet
    container_name: nocountry
    volumes:
      - ./postgres:/var/lib/postgresql/data
